name: Test

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure Git
        run: |
          git config --global user.email "iammadhura26@gmail.com"
          git config --global user.name "madhura"

      - name: Install AWS CDK
        run: npm install -g aws-cdk-lib

      - name: Build CDK app
        run: npm run build
        
      - name: Run tests
        run: npm run test

      - name: Deploy CDK stack
        run: cdk deploy
