name: Test

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm run build
      - name: cdk synth
        run: cdk synth
        
      - name: Deploy code
        run: cdk deploy

      - name: Run tests
        run: npm run test
